terraform {
  required_version = ">= 1.8, < 2.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "4.56.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}

provider "azurerm" {
  features {}
}

data "azurerm_client_config" "current" {}

resource "random_string" "suffix" {
  length  = 6
  special = false
  upper   = false
}

locals {
  location = "westus3"
  tags = {
    tf = "local"
  }
}

resource "azurerm_resource_group" "openai" {
  name     = "rg-openai-${random_string.suffix.result}"
  location = local.location
  tags     = local.tags
}

resource "azurerm_cognitive_account" "openai" {
  name                = "openai${random_string.suffix.result}"
  location            = azurerm_resource_group.openai.location
  resource_group_name = azurerm_resource_group.openai.name
  kind                = "OpenAI"
  sku_name            = "S0"

  public_network_access_enabled = true
  custom_subdomain_name         = "openai${random_string.suffix.result}"

  tags = local.tags
}

resource "azurerm_cognitive_deployment" "gpt_4o_mini" {
  name                 = "gpt-4o-mini"
  cognitive_account_id = azurerm_cognitive_account.openai.id

  model {
    format  = "OpenAI"
    name    = "gpt-4o-mini"
    version = "2024-07-18"
  }

  sku {
    name     = "GlobalStandard"
    capacity = 900
  }
}

resource "azurerm_cognitive_deployment" "gpt_5_1" {
  name                 = "o3"
  cognitive_account_id = azurerm_cognitive_account.openai.id

  model {
    format  = "OpenAI"
    name    = "o3"
    version = "2025-04-16"
  }

  sku {
    name     = "GlobalStandard"
    capacity = 900
  }
}

output "resource_group_name" {
  value       = azurerm_resource_group.openai.name
  description = "Resource group containing Azure OpenAI resources"
}

output "openai_name" {
  value       = azurerm_cognitive_account.openai.name
  description = "Azure OpenAI account name"
}

output "openai_endpoint" {
  value       = azurerm_cognitive_account.openai.endpoint
  description = "Azure OpenAI endpoint"
}

output "gpt_4o_mini_deployment_name" {
  value       = azurerm_cognitive_deployment.gpt_4o_mini.name
  description = "Deployment name for gpt-4o-mini"
}

output "gpt_5_1_deployment_name" {
  value       = azurerm_cognitive_deployment.gpt_5_1.name
  description = "Deployment name for gpt-5.1"
}

output "openai_id" {
  value       = azurerm_cognitive_account.openai.id
  description = "Azure OpenAI account resource ID (used for RBAC scoping)"
}

# Generate .env file for local development
resource "local_file" "env_file" {
  filename = "${path.module}/../../local.env"
  content  = <<-EOT
    # Generated by Terraform - Azure OpenAI local configuration
    AZURE_RESOURCE_GROUP=${azurerm_resource_group.openai.name}
    AZURE_OPENAI_NAME=${azurerm_cognitive_account.openai.name}
    AZURE_OPENAI_ENDPOINT=https://${azurerm_cognitive_account.openai.custom_subdomain_name}.openai.azure.com/
    AZURE_OPENAI_API_VERSION=2024-12-01-preview
    GPT_4O_MINI_DEPLOYMENT=${azurerm_cognitive_deployment.gpt_4o_mini.name}
    GPT_5_1_DEPLOYMENT=${azurerm_cognitive_deployment.gpt_5_1.name}
  EOT
}
