terraform {
  required_version = ">= 1.8, < 2.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "4.56.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "random_string" "suffix" {
  length  = 6
  special = false
  upper   = false
}

locals {
  location = "eastus"
  tags = {
    tf = "local"
  }
}

resource "azurerm_resource_group" "foundry" {
  name     = "rg-foundry-${random_string.suffix.result}"
  location = local.location
  tags     = local.tags
}

# Public Azure AI Foundry account (no VNET, private endpoint, or private DNS)
resource "azurerm_cognitive_account" "ai_foundry" {
  name                = "aifoundry${random_string.suffix.result}"
  location            = azurerm_resource_group.foundry.location
  resource_group_name = azurerm_resource_group.foundry.name
  kind                = "AIServices"
  sku_name            = "S0"

  public_network_access_enabled = true
  custom_subdomain_name         = "aifoundry${random_string.suffix.result}"

  tags = local.tags
}

resource "azurerm_cognitive_deployment" "gpt_4o_mini" {
  name                 = "gpt-4o-mini"
  cognitive_account_id = azurerm_cognitive_account.ai_foundry.id

  model {
    format  = "OpenAI"
    name    = "gpt-4o-mini"
    version = "2024-07-18"
  }

  sku {
    name     = "GlobalStandard"
    capacity = 10
  }
}

resource "azurerm_cognitive_deployment" "gpt_5_1" {
  name                 = "gpt-5-1"
  cognitive_account_id = azurerm_cognitive_account.ai_foundry.id

  model {
    format  = "OpenAI"
    name    = "gpt-5.1"
    version = "2025-04-14"
  }

  sku {
    name     = "GlobalStandard"
    capacity = 10
  }
}

output "resource_group_name" {
  value       = azurerm_resource_group.foundry.name
  description = "Resource group containing Azure AI Foundry resources"
}

output "ai_foundry_name" {
  value       = azurerm_cognitive_account.ai_foundry.name
  description = "Azure AI Foundry account name"
}

output "ai_foundry_endpoint" {
  value       = azurerm_cognitive_account.ai_foundry.endpoint
  description = "Azure AI Foundry endpoint"
}

output "gpt_4o_mini_deployment_name" {
  value       = azurerm_cognitive_deployment.gpt_4o_mini.name
  description = "Deployment name for gpt-4o-mini"
}

output "gpt_5_1_deployment_name" {
  value       = azurerm_cognitive_deployment.gpt_5_1.name
  description = "Deployment name for gpt-5.1"
}

# Generate .env file for local development
resource "local_file" "env_file" {
  filename = "${path.module}/../../.env"
  content  = <<-EOT
    # Generated by Terraform - Azure AI Foundry local configuration
    AZURE_RESOURCE_GROUP=${azurerm_resource_group.foundry.name}

    AI_FOUNDRY_NAME=${azurerm_cognitive_account.ai_foundry.name}
    AI_FOUNDRY_ENDPOINT=${azurerm_cognitive_account.ai_foundry.endpoint}
    GPT_4O_MINI_DEPLOYMENT=${azurerm_cognitive_deployment.gpt_4o_mini.name}
    GPT_5_1_DEPLOYMENT=${azurerm_cognitive_deployment.gpt_5_1.name}
  EOT
}
