properties:
  template:
    scale:
      minReplicas: 1
    containers:
      - name: agent3
        env:
          - name: AGENT_MODEL
            value: gpt-4o-mini
          - name: FABRIC_SQL_ENDPOINT
            value: __FABRIC_SQL_ENDPOINT__
          - name: FABRIC_SQL_DATABASE
            value: postgres-mirror
          - name: AZURE_OPENAI_ENDPOINT
            value: __AZURE_OPENAI_ENDPOINT__
          - name: FABRIC_KQL_CLUSTER_URI
            value: __FABRIC_KQL_CLUSTER_URI__
          - name: FABRIC_KQL_DATABASE
            value: __FABRIC_KQL_DATABASE__
          - name: FABRIC_KQL_TABLE
            value: __FABRIC_KQL_TABLE__
        probes:
          - type: Liveness
            httpGet:
              path: /health
              port: 8003
              scheme: HTTP
          - type: Readiness
            httpGet:
              path: /health
              port: 8003
              scheme: HTTP
