properties:
  template:
    scale:
      minReplicas: 1
    containers:
      - name: agent3
        probes:
          - type: Liveness
            httpGet:
              path: /health
              port: 8003
              scheme: HTTP
          - type: Readiness
            httpGet:
              path: /health
              port: 8003
              scheme: HTTP
