#!/bin/bash
# ============================================================================
# create-fabric-realtime-intelligence.sh
#
# Create Microsoft Fabric Real-Time Intelligence resources:
#   1. Eventhouse  (parent container)
#   2. KQL Database (auto-created child, renamed)
#   3. CustomerReviews table + JSON ingestion mapping
#   4. Eventstream  (wires Event Hub → KQL Database)
#
# The KQL table schema matches the customer_reviews structure in
# event_hubs.duckdb so that events arriving via Azure Event Hub land
# in a queryable KQL database.
#
# Prerequisites:
#   - Azure CLI installed and logged in (az login)
#   - infra/.env with FABRIC_WORKSPACE_ID, EVENTHUB_* variables
#     (generated by 'make tf')
#
# Usage:
#   ./fabric-admin-scripts/create-fabric-realtime-intelligence.sh
# ============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_ROOT/infra/.env"

# Resource names
EVENTHOUSE_DISPLAY_NAME="RetailEventhouse"
KQL_DB_DISPLAY_NAME="CustomerReviewsDB"
EVENTSTREAM_DISPLAY_NAME="ReviewsEventStream"

# ============================================================================
# Helper Functions
# ============================================================================

print_header() {
    echo ""
    echo -e "${BLUE}============================================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}============================================================${NC}"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_info() {
    echo -e "${YELLOW}  $1${NC}"
}

# ============================================================================
# Update .env File
# ============================================================================

update_env_variable() {
    local var_name="$1"
    local var_value="$2"
    local env_file="$ENV_FILE"

    if grep -q "^${var_name}=" "$env_file" 2>/dev/null; then
        if [[ "$(uname)" == "Darwin" ]]; then
            sed -i '' "s|^${var_name}=.*|${var_name}=${var_value}|" "$env_file"
        else
            sed -i "s|^${var_name}=.*|${var_name}=${var_value}|" "$env_file"
        fi
        print_success "Updated ${var_name} in .env"
    else
        echo "${var_name}=${var_value}" >> "$env_file"
        print_success "Added ${var_name} to .env"
    fi
}

# ============================================================================
# Prerequisites Check
# ============================================================================

check_prerequisites() {
    print_header "Checking Prerequisites"

    local missing=0

    # Check Azure CLI
    if ! command -v az &> /dev/null; then
        print_error "Azure CLI (az) is not installed"
        missing=1
    else
        print_success "Azure CLI found"
    fi

    # Check jq (optional but helpful)
    if ! command -v jq &> /dev/null; then
        print_warning "jq not installed (optional, using python fallback)"
    else
        print_success "jq found"
    fi

    # Check if logged into Azure
    if ! az account show &> /dev/null; then
        print_error "Not logged into Azure CLI. Run 'az login' first"
        missing=1
    else
        print_success "Logged into Azure CLI"
    fi

    # Load environment variables
    if [[ -f "$ENV_FILE" ]]; then
        source "$ENV_FILE"
        print_success "Loaded environment from $ENV_FILE"
    else
        print_error ".env file not found at $ENV_FILE"
        print_info "Run 'make tf' to generate it"
        missing=1
    fi

    # Check workspace ID
    if [[ -z "$FABRIC_WORKSPACE_ID" ]]; then
        print_error "FABRIC_WORKSPACE_ID not set in .env"
        missing=1
    else
        print_success "Workspace ID: $FABRIC_WORKSPACE_ID"
    fi

    # Extract Event Hub details from connection string if not directly set
    if [[ -z "$EVENTHUB_NAMESPACE" ]] && [[ -n "$EVENTHUB_CONNECTION_STRING" ]]; then
        EVENTHUB_NAMESPACE=$(echo "$EVENTHUB_CONNECTION_STRING" | grep -o 'Endpoint=sb://[^/]*' | sed 's/Endpoint=sb:\/\///' | sed 's/\.servicebus\.windows\.net//')
    fi

    if [[ -z "$EVENTHUB_NAME" ]] && [[ -n "$EVENTHUB_CONNECTION_STRING" ]]; then
        EVENTHUB_NAME=$(echo "$EVENTHUB_CONNECTION_STRING" | grep -o 'EntityPath=[^;]*' | sed 's/EntityPath=//')
    fi

    if [[ -z "$EVENTHUB_NAMESPACE" ]]; then
        print_warning "EVENTHUB_NAMESPACE not available — Eventstream source must be configured manually"
    else
        print_success "Event Hub Namespace: $EVENTHUB_NAMESPACE"
    fi

    if [[ -z "$EVENTHUB_NAME" ]]; then
        print_warning "EVENTHUB_NAME not available — Eventstream source must be configured manually"
    else
        print_success "Event Hub Name: $EVENTHUB_NAME"
    fi

    if [[ $missing -eq 1 ]]; then
        echo ""
        print_error "Prerequisites check failed. Please fix the above issues."
        exit 1
    fi
}

# ============================================================================
# Get Fabric Access Token
# ============================================================================

get_fabric_token() {
    local token
    token=$(az account get-access-token --resource "https://api.fabric.microsoft.com" --query accessToken -o tsv 2>/dev/null)

    if [[ -z "$token" ]]; then
        print_error "Failed to get Fabric access token"
        exit 1
    fi

    echo "$token"
}

# ============================================================================
# JSON helpers — jq first, python3 fallback
# ============================================================================

json_extract_id() {
    local json="$1"
    local display_name="$2"
    local item_type="$3"

    if command -v jq &> /dev/null; then
        echo "$json" | jq -r ".value[]? | select(.displayName == \"$display_name\" and .type == \"$item_type\") | .id" 2>/dev/null
    else
        echo "$json" | python3 -c "
import sys, json
try:
    items = json.load(sys.stdin).get('value', [])
    result = next((item['id'] for item in items if item.get('displayName') == '$display_name' and item.get('type') == '$item_type'), '')
    print(result)
except:
    print('')
" 2>/dev/null
    fi
}

json_extract_field() {
    local json="$1"
    local field="$2"

    if command -v jq &> /dev/null; then
        echo "$json" | jq -r ".$field // empty" 2>/dev/null
    else
        echo "$json" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    parts = '$field'.split('.')
    for p in parts:
        data = data.get(p, {})
    print(data if isinstance(data, str) else '')
except:
    print('')
" 2>/dev/null
    fi
}

json_extract_first_type_id() {
    local json="$1"
    local item_type="$2"

    if command -v jq &> /dev/null; then
        echo "$json" | jq -r "[.value[]? | select(.type == \"$item_type\")] | first | .id // empty" 2>/dev/null
    else
        echo "$json" | python3 -c "
import sys, json
try:
    items = json.load(sys.stdin).get('value', [])
    result = next((item['id'] for item in items if item.get('type') == '$item_type'), '')
    print(result)
except:
    print('')
" 2>/dev/null
    fi
}

json_extract_first_type_name() {
    local json="$1"
    local item_type="$2"

    if command -v jq &> /dev/null; then
        echo "$json" | jq -r "[.value[]? | select(.type == \"$item_type\")] | first | .displayName // empty" 2>/dev/null
    else
        echo "$json" | python3 -c "
import sys, json
try:
    items = json.load(sys.stdin).get('value', [])
    result = next((item['displayName'] for item in items if item.get('type') == '$item_type'), '')
    print(result)
except:
    print('')
" 2>/dev/null
    fi
}

# ============================================================================
# Create or Get Eventhouse
# ============================================================================

create_eventhouse() {
    local token="$1"

    print_header "Step 1 — Eventhouse"

    local items_url="https://api.fabric.microsoft.com/v1/workspaces/${FABRIC_WORKSPACE_ID}/items"
    local items_response
    items_response=$(curl -s -X GET "$items_url" -H "Authorization: Bearer $token")

    local existing_id
    existing_id=$(json_extract_id "$items_response" "$EVENTHOUSE_DISPLAY_NAME" "Eventhouse")

    if [[ -n "$existing_id" ]]; then
        print_success "Eventhouse '$EVENTHOUSE_DISPLAY_NAME' already exists"
        print_info "Eventhouse ID: $existing_id"
        EVENTHOUSE_ID="$existing_id"
        return 0
    fi

    echo "Creating Eventhouse: $EVENTHOUSE_DISPLAY_NAME ..."

    local payload
    payload=$(cat <<EOF
{
    "displayName": "$EVENTHOUSE_DISPLAY_NAME",
    "type": "Eventhouse",
    "description": "Eventhouse for retail customer reviews real-time data"
}
EOF
)

    local response
    response=$(curl -s -w "\n%{http_code}" -X POST "$items_url" \
        -H "Authorization: Bearer $token" \
        -H "Content-Type: application/json" \
        -d "$payload")

    local http_code
    http_code=$(echo "$response" | tail -n1)
    local body
    body=$(echo "$response" | sed '$d')

    if [[ "$http_code" == "201" || "$http_code" == "200" ]]; then
        EVENTHOUSE_ID=$(json_extract_field "$body" "id")
        print_success "Eventhouse created (ID: $EVENTHOUSE_ID)"
        update_env_variable "FABRIC_EVENTHOUSE_ID" "$EVENTHOUSE_ID"

        print_info "Waiting 45s for Eventhouse provisioning (auto-creates child KQL DB)..."
        sleep 45
    else
        print_error "Failed to create Eventhouse (HTTP $http_code)"
        echo "  $body"
        exit 1
    fi
}

# ============================================================================
# Get Eventhouse Query URI
# ============================================================================

get_eventhouse_query_uri() {
    local token="$1"

    print_header "Step 2 — Eventhouse Query URI"

    local url="https://api.fabric.microsoft.com/v1/workspaces/${FABRIC_WORKSPACE_ID}/eventhouses/${EVENTHOUSE_ID}"
    local response
    response=$(curl -s -X GET "$url" -H "Authorization: Bearer $token")

    KQL_QUERY_URI=$(echo "$response" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    print(data.get('properties', {}).get('queryServiceUri', ''))
except:
    print('')
" 2>/dev/null)

    if [[ -n "$KQL_QUERY_URI" ]]; then
        print_success "Query URI: $KQL_QUERY_URI"
        update_env_variable "KQL_QUERY_URI" "$KQL_QUERY_URI"
    else
        print_warning "Could not retrieve Query URI — may need manual configuration"
    fi
}

# ============================================================================
# Find / Rename KQL Database
# ============================================================================

setup_kql_database() {
    local token="$1"

    print_header "Step 3 — KQL Database"

    local items_url="https://api.fabric.microsoft.com/v1/workspaces/${FABRIC_WORKSPACE_ID}/items"
    local items_response
    items_response=$(curl -s -X GET "$items_url" -H "Authorization: Bearer $token")

    KQL_DB_ID=$(json_extract_first_type_id "$items_response" "KQLDatabase")
    local current_name
    current_name=$(json_extract_first_type_name "$items_response" "KQLDatabase")

    if [[ -z "$KQL_DB_ID" ]]; then
        print_warning "KQL Database not found yet — check Fabric Portal"
        return 1
    fi

    print_success "Found KQL Database: $current_name (ID: $KQL_DB_ID)"
    update_env_variable "FABRIC_KQL_DB_ID" "$KQL_DB_ID"

    # Rename if needed
    if [[ "$current_name" != "$KQL_DB_DISPLAY_NAME" ]]; then
        echo "Renaming KQL Database to '$KQL_DB_DISPLAY_NAME' ..."

        local update_url="https://api.fabric.microsoft.com/v1/workspaces/${FABRIC_WORKSPACE_ID}/items/${KQL_DB_ID}"
        local rename_body="{\"displayName\": \"$KQL_DB_DISPLAY_NAME\"}"

        local update_response
        update_response=$(curl -s -w "\n%{http_code}" -X PATCH "$update_url" \
            -H "Authorization: Bearer $token" \
            -H "Content-Type: application/json" \
            -d "$rename_body")

        local update_code
        update_code=$(echo "$update_response" | tail -n1)

        if [[ "$update_code" == "200" ]]; then
            print_success "KQL Database renamed to $KQL_DB_DISPLAY_NAME"
        else
            print_warning "Could not rename KQL Database (HTTP $update_code)"
        fi
    else
        print_success "KQL Database already named $KQL_DB_DISPLAY_NAME"
    fi
}

# ============================================================================
# Print KQL Table Schema (for manual execution in Fabric Portal)
# ============================================================================

print_kql_schema() {
    print_header "Step 4 — KQL Table Schema"

    echo -e "${YELLOW}Run these commands in the Fabric Portal KQL query editor"
    echo -e "for database: ${KQL_DB_DISPLAY_NAME}${NC}"
    echo ""

    cat <<'KQLEOF'
// ── Create CustomerReviews table ──────────────────────────────
.create table CustomerReviews (
    id: int,
    review_text: string,
    sentiment_category: string,
    sentiment_score: real,
    status: string,
    chatbot_statement: string,
    created_at: datetime,
    processed_at: datetime,
    error_message: string,
    retry_count: int,
    last_retry_at: datetime
) with (folder = "Reviews")

// ── JSON ingestion mapping ────────────────────────────────────
.create table CustomerReviews ingestion json mapping 'CustomerReviewsMapping'
'['
'    {"column":"id",                  "path":"$.id",                  "datatype":"int"},'
'    {"column":"review_text",         "path":"$.review_text",         "datatype":"string"},'
'    {"column":"sentiment_category",  "path":"$.sentiment_category",  "datatype":"string"},'
'    {"column":"sentiment_score",     "path":"$.sentiment_score",     "datatype":"real"},'
'    {"column":"status",              "path":"$.status",              "datatype":"string"},'
'    {"column":"chatbot_statement",   "path":"$.chatbot_statement",   "datatype":"string"},'
'    {"column":"created_at",          "path":"$.created_at",          "datatype":"datetime"},'
'    {"column":"processed_at",        "path":"$.processed_at",        "datatype":"datetime"},'
'    {"column":"error_message",       "path":"$.error_message",       "datatype":"string"},'
'    {"column":"retry_count",         "path":"$.retry_count",         "datatype":"int"},'
'    {"column":"last_retry_at",       "path":"$.last_retry_at",       "datatype":"datetime"}'
']'

// ── Enable streaming ingestion ────────────────────────────────
.alter table CustomerReviews policy streamingingestion enable

// ── 90-day hot cache ──────────────────────────────────────────
.alter table CustomerReviews policy caching hot = 90d
KQLEOF

    echo ""
}

# ============================================================================
# Create Eventstream
# ============================================================================

create_eventstream() {
    local token="$1"

    print_header "Step 5 — Eventstream"

    local items_url="https://api.fabric.microsoft.com/v1/workspaces/${FABRIC_WORKSPACE_ID}/items"
    local items_response
    items_response=$(curl -s -X GET "$items_url" -H "Authorization: Bearer $token")

    local existing_id
    existing_id=$(json_extract_id "$items_response" "$EVENTSTREAM_DISPLAY_NAME" "Eventstream")

    if [[ -n "$existing_id" ]]; then
        print_success "Eventstream '$EVENTSTREAM_DISPLAY_NAME' already exists"
        print_info "Eventstream ID: $existing_id"
        EVENTSTREAM_ID="$existing_id"
        return 0
    fi

    echo "Creating Eventstream: $EVENTSTREAM_DISPLAY_NAME ..."

    local payload
    payload=$(cat <<EOF
{
    "displayName": "$EVENTSTREAM_DISPLAY_NAME",
    "type": "Eventstream",
    "description": "Streams customer review events from Azure Event Hub to KQL Database"
}
EOF
)

    local response
    response=$(curl -s -w "\n%{http_code}" -X POST "$items_url" \
        -H "Authorization: Bearer $token" \
        -H "Content-Type: application/json" \
        -d "$payload")

    local http_code
    http_code=$(echo "$response" | tail -n1)
    local body
    body=$(echo "$response" | sed '$d')

    if [[ "$http_code" == "201" || "$http_code" == "200" || "$http_code" == "202" ]]; then
        EVENTSTREAM_ID=$(json_extract_field "$body" "id")
        print_success "Eventstream created (ID: ${EVENTSTREAM_ID:-pending})"
        if [[ "$http_code" == "202" ]]; then
            print_info "Async provisioning in progress"
        fi
    else
        print_error "Failed to create Eventstream (HTTP $http_code)"
        echo "  $body"
        exit 1
    fi
}

# ============================================================================
# Manual Wiring Instructions
# ============================================================================

print_manual_steps() {
    print_header "Manual Configuration — Eventstream Wiring"

    echo -e "${YELLOW}In Fabric Portal, open Eventstream: $EVENTSTREAM_DISPLAY_NAME${NC}"
    echo ""
    echo "  ADD SOURCE — Azure Event Hub"
    echo "    Click 'New connection'"
    echo "    Event Hub namespace: ${EVENTHUB_NAMESPACE:-<from .env>}.servicebus.windows.net"
    echo "    Event Hub:           ${EVENTHUB_NAME:-<from .env>}"
    echo "    Auth:                Shared Access Key"
    echo "    Key Name:            RootManageSharedAccessKey"
    if [[ -n "$EVENTHUB_CONNECTION_STRING" ]]; then
        local sas_key
        sas_key=$(echo "$EVENTHUB_CONNECTION_STRING" | grep -o 'SharedAccessKey=[^;]*' | sed 's/SharedAccessKey=//')
        echo "    Key Value:           $sas_key"
    else
        echo "    Key Value:           (get from infra/.env — EVENTHUB_CONNECTION_STRING)"
    fi
    echo "    Consumer Group:      \$Default"
    echo "    Data format:         Json"
    echo ""
    echo "  ADD DESTINATION — KQL Database"
    echo "    Workspace:       (select your workspace)"
    echo "    KQL Database:    $KQL_DB_DISPLAY_NAME"
    echo "    Table:           CustomerReviews"
    echo "    Input format:    Json"
    echo "    Mapping:         CustomerReviewsMapping"
    echo ""
    echo "  Then click Publish to activate the Eventstream."
    echo ""

    print_header "Next Steps"
    echo "  1. Run the KQL table schema commands (Step 4 output above)"
    echo "  2. Wire the Eventstream source + destination (instructions above)"
    echo "  3. Run simulation:  make run-simulation-quick"
    echo "  4. Verify in KQL:   CustomerReviews | take 10"
}

# ============================================================================
# Main
# ============================================================================

main() {
    print_header "Fabric Real-Time Intelligence Setup"

    check_prerequisites

    print_header "Authenticating with Fabric"
    local token
    token=$(get_fabric_token)
    print_success "Obtained Fabric access token"

    create_eventhouse "$token"
    get_eventhouse_query_uri "$token"
    setup_kql_database "$token"
    print_kql_schema
    create_eventstream "$token"
    print_manual_steps

    echo ""
    print_success "Real-Time Intelligence setup complete!"
}

main "$@"
