"""
Sync pipeline configuration.

Loads cloud settings from infra/.env (generated by Terraform) and exposes
local DuckDB paths and staging storage configuration.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# ---------------------------------------------------------------------------
# Load the Terraform-generated .env file (infra/.env)
# ---------------------------------------------------------------------------
_REPO_ROOT = Path(__file__).resolve().parents[1]
_CLOUD_ENV = _REPO_ROOT / "infra" / ".env"

if _CLOUD_ENV.exists():
    load_dotenv(_CLOUD_ENV, override=False)

# ---------------------------------------------------------------------------
# Local DuckDB paths (same defaults as simulation/shared/local_backend.py)
# ---------------------------------------------------------------------------
LOCAL_POSTGRES_DB = os.environ.get(
    "LOCAL_POSTGRES_DB", str(_REPO_ROOT / "local_postgres.duckdb")
)
LOCAL_COSMOS_DB = os.environ.get(
    "LOCAL_COSMOS_DB", str(_REPO_ROOT / "local_cosmos.duckdb")
)
EVENT_HUBS_DB = os.environ.get(
    "EVENT_HUBS_DB", str(_REPO_ROOT / "event_hubs.duckdb")
)

# ---------------------------------------------------------------------------
# Staging output directory (local filesystem before upload)
# ---------------------------------------------------------------------------
STAGING_DIR = _REPO_ROOT / "sync" / "staging"

# ---------------------------------------------------------------------------
# Azure Blob Storage (staging area in the cloud)
# ---------------------------------------------------------------------------
STAGING_STORAGE_ACCOUNT = os.environ.get("STAGING_STORAGE_ACCOUNT", "")
STAGING_STORAGE_CONN_STRING = os.environ.get("STAGING_STORAGE_CONN_STRING", "")

# Blob container names inside the staging storage account
STAGING_CONTAINER_POSTGRES = "postgres"
STAGING_CONTAINER_COSMOS = "cosmos"
STAGING_CONTAINER_EVENTHUB = "eventhub"
