import { MetricData, MetricBreakdown } from './types'
import { TabId } from '../components/NavigationSidebar'

// ---------------------------------------------------------------------------
// Registry interfaces
// ---------------------------------------------------------------------------

export interface RegistryDriver {
  id: string
  label: string
  formula: string
  sourceTable: string
  description: string
  format: 'number' | 'currency' | 'percentage'
  seedValue: number
  seedContribution: number
  seedTrend: 'up' | 'down' | 'neutral'
  seedChangePercent: number
}

export interface RegistryMetric {
  id: string
  label: string
  format: 'number' | 'currency' | 'percentage'
  unit: string
  icon: string
  sourceTable: string
  sql: string
  invertTrend: boolean
  seedValue: number
  seedPreviousValue: number
  forecast?: { value: number; variance: number; variancePercent: number }
  drivers: RegistryDriver[]
  insights: string[]
}

// ---------------------------------------------------------------------------
// Main tab — 6 tiles
// ---------------------------------------------------------------------------

const mainMetrics: RegistryMetric[] = [
  {
    id: 'revenue',
    label: 'Total Revenue',
    format: 'currency',
    unit: '$',
    icon: 'currency',
    sourceTable: 'customer_journeys',
    sql: 'SELECT SUM(total_amount) FROM customer_journeys WHERE completed = TRUE',
    invertTrend: false,
    seedValue: 284750,
    seedPreviousValue: 267200,
    drivers: [
      {
        id: 'rev-order-volume',
        label: 'Order Volume',
        formula: 'COUNT(*) WHERE completed = TRUE',
        sourceTable: 'customer_journeys',
        description: 'More orders = more revenue; driven by traffic and conversion',
        format: 'number',
        seedValue: 1847,
        seedContribution: 35.2,
        seedTrend: 'down',
        seedChangePercent: 3.9,
      },
      {
        id: 'rev-aov',
        label: 'Average Order Value',
        formula: 'AVG(total_amount) WHERE completed = TRUE',
        sourceTable: 'customer_journeys',
        description: 'Higher basket value lifts revenue without needing more traffic',
        format: 'currency',
        seedValue: 154.23,
        seedContribution: 28.4,
        seedTrend: 'up',
        seedChangePercent: 11.0,
      },
      {
        id: 'rev-basket-size',
        label: 'Basket Size',
        formula: 'AVG(basket_size) WHERE completed = TRUE',
        sourceTable: 'customer_journeys',
        description: 'Larger baskets directly increase order value',
        format: 'number',
        seedValue: 3.8,
        seedContribution: 15.6,
        seedTrend: 'up',
        seedChangePercent: 4.2,
      },
      {
        id: 'rev-unit-price',
        label: 'Average Unit Price',
        formula: 'SUM(total_amount) / SUM(basket_size)',
        sourceTable: 'customer_journeys',
        description: 'Product mix shift toward premium items raises AOV',
        format: 'currency',
        seedValue: 40.59,
        seedContribution: 12.1,
        seedTrend: 'up',
        seedChangePercent: 2.8,
      },
      {
        id: 'rev-channel-mix',
        label: 'Channel Mix',
        formula: 'SUM(total_amount) GROUP BY channel',
        sourceTable: 'customer_journeys',
        description: 'Online vs in-store vs BOPIS have different AOVs and conversion rates',
        format: 'currency',
        seedValue: 284750,
        seedContribution: 8.7,
        seedTrend: 'up',
        seedChangePercent: 5.1,
      },
    ],
    insights: [
      'AOV growth of 11% is the primary revenue driver, offsetting a slight dip in order volume',
      'Channel mix is shifting toward online, which carries a higher average basket size',
      'Basket size trending up at 4.2%, indicating successful cross-sell and upsell strategies',
    ],
  },
  {
    id: 'customers',
    label: 'Total Customers',
    format: 'number',
    unit: '',
    icon: 'users',
    sourceTable: 'customer_snapshots',
    sql: 'SELECT COUNT(DISTINCT customer_id) FROM customer_snapshots',
    invertTrend: false,
    seedValue: 54012,
    seedPreviousValue: 52890,
    drivers: [
      {
        id: 'cust-active',
        label: 'Active Customers',
        formula: "COUNT(*) WHERE activity_state = 'active'",
        sourceTable: 'customer_snapshots',
        description: 'Customers with recent purchase activity',
        format: 'number',
        seedValue: 36968,
        seedContribution: 68.4,
        seedTrend: 'up',
        seedChangePercent: 2.8,
      },
      {
        id: 'cust-lapsed',
        label: 'Lapsed Customers',
        formula: "COUNT(*) WHERE activity_state = 'lapsed'",
        sourceTable: 'customer_snapshots',
        description: 'Customers who have not purchased within the active threshold',
        format: 'number',
        seedValue: 12643,
        seedContribution: 23.4,
        seedTrend: 'up',
        seedChangePercent: 1.5,
      },
      {
        id: 'cust-churned',
        label: 'Churned Customers',
        formula: 'COUNT(*) WHERE churned = TRUE',
        sourceTable: 'customer_snapshots',
        description: 'Customers lost due to engagement decay and unresponsiveness',
        format: 'number',
        seedValue: 4429,
        seedContribution: 8.2,
        seedTrend: 'up',
        seedChangePercent: 3.1,
      },
      {
        id: 'cust-value-tier',
        label: 'By Value Tier',
        formula: 'COUNT(*) GROUP BY value_tier',
        sourceTable: 'customer_snapshots',
        description: 'Distribution across VIP, High, Medium, Low tiers',
        format: 'number',
        seedValue: 54012,
        seedContribution: 0,
        seedTrend: 'neutral',
        seedChangePercent: 0,
      },
    ],
    insights: [
      'Active customer base growing at 2.8%, healthy sign for retention',
      'Churned segment growing at 3.1% — re-engagement campaigns should target this group',
      'Lapsed customers represent 23.4% of the base, a reactivation opportunity',
    ],
  },
  {
    id: 'conversion',
    label: 'Conversion Rate',
    format: 'percentage',
    unit: '%',
    icon: 'trend',
    sourceTable: 'customer_journeys',
    sql: 'SELECT COUNT(CASE WHEN completed THEN 1 END) * 100.0 / COUNT(*) FROM customer_journeys',
    invertTrend: false,
    seedValue: 3.42,
    seedPreviousValue: 3.21,
    drivers: [
      {
        id: 'conv-cart-abandon',
        label: 'Cart Abandonment Rate',
        formula: 'COUNT(WHERE abandoned) / COUNT(*)',
        sourceTable: 'customer_journeys',
        description: 'Primary leak in the funnel',
        format: 'percentage',
        seedValue: 24.8,
        seedContribution: 38.5,
        seedTrend: 'down',
        seedChangePercent: 2.4,
      },
      {
        id: 'conv-abandon-reason',
        label: 'Abandonment by Reason',
        formula: 'COUNT(*) GROUP BY abandonment_reason',
        sourceTable: 'customer_journeys',
        description: 'Identifies whether abandonment is due to price, wait time, or browsing fatigue',
        format: 'number',
        seedValue: 458,
        seedContribution: 22.1,
        seedTrend: 'down',
        seedChangePercent: 3.8,
      },
      {
        id: 'conv-payment-fail',
        label: 'Payment Failure Rate',
        formula: 'COUNT(WHERE payment_failed) / COUNT(*)',
        sourceTable: 'customer_journeys',
        description: 'Technical failures that block otherwise willing buyers',
        format: 'percentage',
        seedValue: 3.2,
        seedContribution: 15.3,
        seedTrend: 'down',
        seedChangePercent: 0.8,
      },
      {
        id: 'conv-queue-balk',
        label: 'Queue Balk Rate',
        formula: "COUNT(WHERE abandonment_reason = 'queue_too_long') / in_store_count",
        sourceTable: 'customer_journeys',
        description: 'In-store customers who leave because the line is too long',
        format: 'percentage',
        seedValue: 5.1,
        seedContribution: 12.8,
        seedTrend: 'neutral',
        seedChangePercent: 0.3,
      },
      {
        id: 'conv-browsing-dur',
        label: 'Browsing Duration',
        formula: 'AVG(browsing_duration)',
        sourceTable: 'customer_journeys',
        description: 'Longer browsing can indicate engagement or friction',
        format: 'number',
        seedValue: 8.4,
        seedContribution: 11.3,
        seedTrend: 'up',
        seedChangePercent: 1.2,
      },
    ],
    insights: [
      'Cart abandonment declining 2.4%, the biggest lever for conversion improvement',
      'Payment failure rate at 3.2% represents preventable lost sales — gateway optimization recommended',
      'Conversion improved 6.5% period-over-period, driven by reduced abandonment and better checkout flow',
    ],
  },
  {
    id: 'aov',
    label: 'Average Order Value',
    format: 'currency',
    unit: '$',
    icon: 'cart',
    sourceTable: 'customer_journeys',
    sql: 'SELECT AVG(total_amount) FROM customer_journeys WHERE completed = TRUE',
    invertTrend: false,
    seedValue: 154.23,
    seedPreviousValue: 138.95,
    drivers: [
      {
        id: 'aov-basket',
        label: 'Basket Size',
        formula: 'AVG(basket_size)',
        sourceTable: 'customer_journeys',
        description: 'Number of items per order',
        format: 'number',
        seedValue: 3.8,
        seedContribution: 42.3,
        seedTrend: 'up',
        seedChangePercent: 4.2,
      },
      {
        id: 'aov-unit-price',
        label: 'Unit Price Distribution',
        formula: 'AVG(unit_price)',
        sourceTable: 'order_items',
        description: 'Average price per item across all orders',
        format: 'currency',
        seedValue: 40.59,
        seedContribution: 31.8,
        seedTrend: 'up',
        seedChangePercent: 3.8,
      },
      {
        id: 'aov-category-mix',
        label: 'Product Category Mix',
        formula: 'SUM(subtotal) GROUP BY category',
        sourceTable: 'order_items',
        description: 'Shift toward higher-value categories lifts AOV',
        format: 'currency',
        seedValue: 154.23,
        seedContribution: 17.4,
        seedTrend: 'up',
        seedChangePercent: 6.1,
      },
      {
        id: 'aov-channel',
        label: 'Channel Effect',
        formula: 'AVG(total_amount) GROUP BY channel',
        sourceTable: 'customer_journeys',
        description: 'Online orders tend to have higher AOV than in-store',
        format: 'currency',
        seedValue: 154.23,
        seedContribution: 8.5,
        seedTrend: 'up',
        seedChangePercent: 2.3,
      },
    ],
    insights: [
      'AOV up 11% driven by larger basket sizes and premium product mix shift',
      'Category mix shifting toward higher-value items, contributing 6.1% growth',
      'Online channel averaging $168 per order vs $132 in-store, widening the gap',
    ],
  },
  {
    id: 'clv',
    label: 'Customer Lifetime Value',
    format: 'currency',
    unit: '$',
    icon: 'currency',
    sourceTable: 'customer_snapshots',
    sql: 'SELECT AVG(total_spend) FROM customer_snapshots WHERE total_spend > 0',
    invertTrend: false,
    seedValue: 1247.50,
    seedPreviousValue: 1189.30,
    drivers: [
      {
        id: 'clv-frequency',
        label: 'Purchase Frequency',
        formula: 'AVG(purchase_count)',
        sourceTable: 'customer_snapshots',
        description: 'More frequent purchases increase lifetime value',
        format: 'number',
        seedValue: 8.1,
        seedContribution: 32.4,
        seedTrend: 'up',
        seedChangePercent: 3.2,
      },
      {
        id: 'clv-aov',
        label: 'Average Order Value',
        formula: 'AVG(avg_order_value)',
        sourceTable: 'customer_snapshots',
        description: 'Higher per-order spend compounds over the customer lifetime',
        format: 'currency',
        seedValue: 154.01,
        seedContribution: 28.7,
        seedTrend: 'up',
        seedChangePercent: 5.1,
      },
      {
        id: 'clv-tenure',
        label: 'Customer Tenure',
        formula: 'AVG(days_since_join)',
        sourceTable: 'customer_snapshots',
        description: 'Longer customer relationships accumulate more value',
        format: 'number',
        seedValue: 284,
        seedContribution: 18.3,
        seedTrend: 'up',
        seedChangePercent: 1.8,
      },
      {
        id: 'clv-loyalty',
        label: 'Loyalty Points Balance',
        formula: 'AVG(loyalty_points)',
        sourceTable: 'customer_snapshots',
        description: 'Active loyalty engagement correlates with higher spend',
        format: 'number',
        seedValue: 2340,
        seedContribution: 12.1,
        seedTrend: 'up',
        seedChangePercent: 4.7,
      },
      {
        id: 'clv-churn-risk',
        label: 'Churn Risk Score',
        formula: 'AVG(churn_risk_score)',
        sourceTable: 'customer_snapshots',
        description: 'Higher risk scores reduce expected future revenue',
        format: 'number',
        seedValue: 0.23,
        seedContribution: 8.5,
        seedTrend: 'down',
        seedChangePercent: 1.4,
      },
    ],
    insights: [
      'CLV up 4.9% driven by increasing purchase frequency and rising AOV',
      'Loyalty members show 2.3x higher CLV than non-members, validating program investment',
      'Declining churn risk score is a positive signal for long-term customer value retention',
    ],
  },
  {
    id: 'return-rate',
    label: 'Return Rate',
    format: 'percentage',
    unit: '%',
    icon: 'package',
    sourceTable: 'order_metrics',
    sql: 'SELECT COUNT(CASE WHEN returned THEN 1 END) * 100.0 / COUNT(*) FROM order_metrics',
    invertTrend: true,
    seedValue: 2.80,
    seedPreviousValue: 3.10,
    drivers: [
      {
        id: 'ret-by-channel',
        label: 'Returns by Channel',
        formula: 'COUNT(WHERE returned) GROUP BY channel',
        sourceTable: 'order_metrics',
        description: 'Online returns are higher due to fit uncertainty',
        format: 'percentage',
        seedValue: 2.80,
        seedContribution: 42.9,
        seedTrend: 'down',
        seedChangePercent: 8.3,
      },
      {
        id: 'ret-by-day',
        label: 'Returns by Day of Week',
        formula: 'COUNT(WHERE returned) GROUP BY day_of_week',
        sourceTable: 'order_metrics',
        description: 'Post-weekend returns peak on Monday/Tuesday',
        format: 'number',
        seedValue: 47,
        seedContribution: 21.4,
        seedTrend: 'down',
        seedChangePercent: 5.2,
      },
      {
        id: 'ret-late-delivery',
        label: 'Late Delivery Effect',
        formula: 'return_rate WHERE on_time = FALSE vs on_time = TRUE',
        sourceTable: 'order_metrics',
        description: 'Late deliveries have significantly higher return rates',
        format: 'percentage',
        seedValue: 8.4,
        seedContribution: 23.8,
        seedTrend: 'down',
        seedChangePercent: 12.5,
      },
      {
        id: 'ret-fulfillment-dur',
        label: 'Fulfillment Duration Effect',
        formula: 'AVG(fulfillment_duration) WHERE returned vs NOT returned',
        sourceTable: 'order_metrics',
        description: 'Longer fulfillment correlates with higher return likelihood',
        format: 'number',
        seedValue: 3.2,
        seedContribution: 11.9,
        seedTrend: 'down',
        seedChangePercent: 4.8,
      },
    ],
    insights: [
      'Return rate improved 9.7% — late delivery reduction is the strongest contributor',
      'Online channel still has 2x return rate vs in-store, improved size guides are helping',
      'Fulfillment speed improvements correlated with lower return likelihood across all channels',
    ],
  },
]

// ---------------------------------------------------------------------------
// Omnichannel tab — 8 tiles
// ---------------------------------------------------------------------------

const omnichannelMetrics: RegistryMetric[] = [
  {
    id: 'omni-arrival-rate',
    label: 'Arrival Rate',
    format: 'number',
    unit: '/hr',
    icon: 'users',
    sourceTable: 'customer_journeys',
    sql: 'SELECT COUNT(*) / simulation_hours FROM customer_journeys',
    invertTrend: false,
    seedValue: 342,
    seedPreviousValue: 328,
    drivers: [
      {
        id: 'omni-arr-hourly-count',
        label: 'Hourly Arrival Count',
        formula: 'arrival_count',
        sourceTable: 'hourly_demand',
        description: 'Raw arrival count per simulation hour',
        format: 'number',
        seedValue: 342,
        seedContribution: 32.1,
        seedTrend: 'up',
        seedChangePercent: 4.3,
      },
      {
        id: 'omni-arr-hourly-rev',
        label: 'Hourly Revenue',
        formula: 'revenue',
        sourceTable: 'hourly_demand',
        description: 'Revenue generated per hour, driven by arrivals and conversion',
        format: 'currency',
        seedValue: 11862,
        seedContribution: 28.4,
        seedTrend: 'up',
        seedChangePercent: 6.6,
      },
      {
        id: 'omni-arr-hourly-orders',
        label: 'Hourly Order Count',
        formula: 'order_count',
        sourceTable: 'hourly_demand',
        description: 'Orders per hour = arrivals x conversion rate',
        format: 'number',
        seedValue: 77,
        seedContribution: 22.8,
        seedTrend: 'up',
        seedChangePercent: 3.1,
      },
      {
        id: 'omni-arr-abandon',
        label: 'Hourly Abandonment Count',
        formula: 'abandonment_count',
        sourceTable: 'hourly_demand',
        description: 'Peaks during high-traffic hours when queues are long',
        format: 'number',
        seedValue: 82,
        seedContribution: 16.7,
        seedTrend: 'down',
        seedChangePercent: 2.1,
      },
    ],
    insights: [
      'Arrival rate up 4.3%, indicating growing brand awareness and traffic acquisition',
      'Hourly revenue growing faster than arrivals, suggesting higher conversion per visitor',
      'Abandonment declining despite higher traffic, reflecting improved checkout experience',
    ],
  },
  {
    id: 'omni-conversion',
    label: 'Conversion Rate',
    format: 'percentage',
    unit: '%',
    icon: 'trend',
    sourceTable: 'customer_journeys',
    sql: 'SELECT completed / total_journeys FROM customer_journeys',
    invertTrend: false,
    seedValue: 3.42,
    seedPreviousValue: 3.21,
    drivers: [
      {
        id: 'omni-conv-by-channel',
        label: 'Conversion by Channel',
        formula: 'completed / total per channel',
        sourceTable: 'customer_journeys',
        description: 'Online has highest abandonment; in-store has queue balking',
        format: 'percentage',
        seedValue: 3.42,
        seedContribution: 40.2,
        seedTrend: 'up',
        seedChangePercent: 6.5,
      },
      {
        id: 'omni-conv-payment-fail',
        label: 'Payment Failure Rate',
        formula: 'payment_failed / total_journeys',
        sourceTable: 'customer_journeys',
        description: 'Payment method distribution and gateway reliability',
        format: 'percentage',
        seedValue: 3.2,
        seedContribution: 32.6,
        seedTrend: 'down',
        seedChangePercent: 0.8,
      },
      {
        id: 'omni-conv-balk',
        label: 'Queue Balk Rate',
        formula: 'balked / in_store_arrivals',
        sourceTable: 'customer_journeys',
        description: 'In-store customers leaving due to long queues',
        format: 'percentage',
        seedValue: 5.1,
        seedContribution: 27.2,
        seedTrend: 'neutral',
        seedChangePercent: 0.3,
      },
    ],
    insights: [
      'Overall conversion up 6.5%, strongest gains in online channel',
      'Payment failure rate stable at 3.2%, gateway optimization could yield further gains',
      'Queue balk rate unchanged — consider adding checkout counters during peak hours',
    ],
  },
  {
    id: 'omni-cart-abandon',
    label: 'Cart Abandonment Rate',
    format: 'percentage',
    unit: '%',
    icon: 'cart',
    sourceTable: 'customer_journeys',
    sql: 'SELECT abandoned / total_journeys FROM customer_journeys',
    invertTrend: true,
    seedValue: 24.8,
    seedPreviousValue: 26.1,
    drivers: [
      {
        id: 'omni-cart-price',
        label: 'Price Sensitivity',
        formula: "COUNT(*) WHERE abandonment_reason = 'price'",
        sourceTable: 'customer_journeys',
        description: 'Customers who abandon due to price being too high',
        format: 'number',
        seedValue: 186,
        seedContribution: 38.2,
        seedTrend: 'down',
        seedChangePercent: 3.4,
      },
      {
        id: 'omni-cart-queue',
        label: 'Queue Too Long',
        formula: "COUNT(*) WHERE abandonment_reason = 'queue_too_long'",
        sourceTable: 'customer_journeys',
        description: 'In-store customers who balk at the checkout line',
        format: 'number',
        seedValue: 94,
        seedContribution: 24.8,
        seedTrend: 'down',
        seedChangePercent: 1.2,
      },
      {
        id: 'omni-cart-browse',
        label: 'Browsing Fatigue',
        formula: "COUNT(*) WHERE abandonment_reason = 'browsing_fatigue'",
        sourceTable: 'customer_journeys',
        description: 'Customers who leave after browsing without intent to buy',
        format: 'number',
        seedValue: 142,
        seedContribution: 36.9,
        seedTrend: 'down',
        seedChangePercent: 2.8,
      },
    ],
    insights: [
      'Cart abandonment declining 5.0% — price sensitivity is the largest but shrinking driver',
      'Queue-related abandonment improved 1.2%, small but consistent gains',
      'Browsing fatigue declining, suggesting better product discovery and site navigation',
    ],
  },
  {
    id: 'omni-avg-journey',
    label: 'Avg Journey Time',
    format: 'number',
    unit: 'min',
    icon: 'clock',
    sourceTable: 'customer_journeys',
    sql: 'SELECT AVG(total_journey_time) FROM customer_journeys',
    invertTrend: true,
    seedValue: 14.2,
    seedPreviousValue: 15.8,
    drivers: [
      {
        id: 'omni-jour-browse',
        label: 'Avg Browsing Duration',
        formula: 'AVG(browsing_duration)',
        sourceTable: 'customer_journeys',
        description: 'Time spent browsing products before adding to cart',
        format: 'number',
        seedValue: 8.4,
        seedContribution: 42.1,
        seedTrend: 'down',
        seedChangePercent: 5.2,
      },
      {
        id: 'omni-jour-queue',
        label: 'Avg Queue Wait Time',
        formula: 'AVG(queue_wait_time)',
        sourceTable: 'customer_journeys',
        description: 'Wait time driven by checkout counter capacity and arrival rate',
        format: 'number',
        seedValue: 3.1,
        seedContribution: 28.4,
        seedTrend: 'down',
        seedChangePercent: 8.3,
      },
      {
        id: 'omni-jour-checkout',
        label: 'Avg Checkout Time',
        formula: 'AVG(checkout_time)',
        sourceTable: 'customer_journeys',
        description: 'Time to complete the checkout/payment process',
        format: 'number',
        seedValue: 2.7,
        seedContribution: 29.5,
        seedTrend: 'down',
        seedChangePercent: 4.1,
      },
    ],
    insights: [
      'Journey time reduced 10.1%, improving customer experience across all stages',
      'Queue wait time improved the most at 8.3%, likely from added checkout capacity',
      'Faster browsing suggests improved site navigation and product discovery',
    ],
  },
  {
    id: 'omni-total-orders',
    label: 'Total Orders',
    format: 'number',
    unit: '',
    icon: 'shopping',
    sourceTable: 'order_metrics',
    sql: 'SELECT COUNT(*) FROM order_metrics',
    invertTrend: false,
    seedValue: 1847,
    seedPreviousValue: 1923,
    forecast: { value: 1950, variance: 103, variancePercent: 5.58 },
    drivers: [
      {
        id: 'omni-ord-by-channel',
        label: 'Orders by Channel',
        formula: 'COUNT(*) GROUP BY channel',
        sourceTable: 'order_metrics',
        description: 'Channel-specific traffic and conversion drive order distribution',
        format: 'number',
        seedValue: 1847,
        seedContribution: 42.3,
        seedTrend: 'down',
        seedChangePercent: 3.9,
      },
      {
        id: 'omni-ord-by-time',
        label: 'Orders by Time of Day',
        formula: 'COUNT(*) GROUP BY order_hour',
        sourceTable: 'order_metrics',
        description: 'Peak hours drive order volume, with lunch and evening spikes',
        format: 'number',
        seedValue: 1847,
        seedContribution: 28.8,
        seedTrend: 'down',
        seedChangePercent: 2.1,
      },
      {
        id: 'omni-ord-basket',
        label: 'Avg Basket Size',
        formula: 'AVG(basket_size) WHERE completed',
        sourceTable: 'customer_journeys',
        description: 'Product mix and shopping behavior drive basket size',
        format: 'number',
        seedValue: 3.8,
        seedContribution: 18.2,
        seedTrend: 'up',
        seedChangePercent: 4.2,
      },
      {
        id: 'omni-ord-payment',
        label: 'Payment Method Distribution',
        formula: 'COUNT(*) GROUP BY payment_method',
        sourceTable: 'payments',
        description: 'Credit card, debit card, and PayPal shares',
        format: 'number',
        seedValue: 1847,
        seedContribution: 10.7,
        seedTrend: 'neutral',
        seedChangePercent: 0.5,
      },
    ],
    insights: [
      'Order volume down 3.9% but AOV up, so revenue impact is offset',
      'Basket size growing at 4.2%, compensating for lower order counts',
      'Forecast predicts recovery to 1,950 orders with 5.6% upside variance',
    ],
  },
  {
    id: 'omni-ontime',
    label: 'On-Time Delivery %',
    format: 'percentage',
    unit: '%',
    icon: 'check',
    sourceTable: 'order_metrics',
    sql: 'SELECT COUNT(WHERE on_time) / COUNT(*) FROM order_metrics',
    invertTrend: false,
    seedValue: 91.3,
    seedPreviousValue: 88.7,
    drivers: [
      {
        id: 'omni-ot-late',
        label: 'Late Orders',
        formula: 'COUNT(WHERE on_time = FALSE)',
        sourceTable: 'order_metrics',
        description: 'Absolute count of orders missing SLA',
        format: 'number',
        seedValue: 161,
        seedContribution: 35.4,
        seedTrend: 'down',
        seedChangePercent: 18.2,
      },
      {
        id: 'omni-ot-by-channel',
        label: 'Fulfillment by Channel',
        formula: 'AVG(fulfillment_duration) GROUP BY channel',
        sourceTable: 'order_metrics',
        description: 'BOPIS is fastest; online depends on warehouse capacity',
        format: 'number',
        seedValue: 2.4,
        seedContribution: 32.8,
        seedTrend: 'down',
        seedChangePercent: 8.4,
      },
      {
        id: 'omni-ot-return-rate',
        label: 'Return Rate',
        formula: 'COUNT(WHERE returned) / COUNT(*)',
        sourceTable: 'order_metrics',
        description: 'Category-specific return rates from config',
        format: 'percentage',
        seedValue: 2.80,
        seedContribution: 31.8,
        seedTrend: 'down',
        seedChangePercent: 9.7,
      },
    ],
    insights: [
      'On-time delivery improved 2.9pp, driven by 18.2% fewer late orders',
      'BOPIS channel averaging 0.5-day fulfillment, pulling overall average down',
      'Return rate improvement supports fewer reverse-logistics disruptions',
    ],
  },
  {
    id: 'omni-fulfillment-dur',
    label: 'Avg Fulfillment Duration',
    format: 'number',
    unit: 'days',
    icon: 'clock',
    sourceTable: 'order_metrics',
    sql: 'SELECT AVG(fulfillment_duration) FROM order_metrics',
    invertTrend: true,
    seedValue: 2.4,
    seedPreviousValue: 2.8,
    drivers: [
      {
        id: 'omni-ful-by-channel',
        label: 'Duration by Channel',
        formula: 'AVG(fulfillment_duration) GROUP BY channel',
        sourceTable: 'order_metrics',
        description: 'BOPIS is fastest; online depends on warehouse capacity',
        format: 'number',
        seedValue: 2.4,
        seedContribution: 44.2,
        seedTrend: 'down',
        seedChangePercent: 14.3,
      },
      {
        id: 'omni-ful-ontime',
        label: 'On-Time Delivery %',
        formula: 'COUNT(WHERE on_time) / COUNT(*)',
        sourceTable: 'order_metrics',
        description: 'Fulfillment speed directly impacts SLA adherence',
        format: 'percentage',
        seedValue: 91.3,
        seedContribution: 33.6,
        seedTrend: 'up',
        seedChangePercent: 2.9,
      },
      {
        id: 'omni-ful-late',
        label: 'Late Orders',
        formula: 'COUNT(WHERE on_time = FALSE)',
        sourceTable: 'order_metrics',
        description: 'Orders that missed their delivery SLA',
        format: 'number',
        seedValue: 161,
        seedContribution: 22.2,
        seedTrend: 'down',
        seedChangePercent: 18.2,
      },
    ],
    insights: [
      'Fulfillment duration improved 14.3%, strongest improvement in online channel',
      'BOPIS fulfillment averaging 0.5 days, significantly faster than ship-from-warehouse',
      'Late orders reduced 18.2%, indicating systemic improvement in warehouse operations',
    ],
  },
  {
    id: 'omni-payment-success',
    label: 'Payment Success Rate',
    format: 'percentage',
    unit: '%',
    icon: 'check',
    sourceTable: 'payments',
    sql: "SELECT COUNT(WHERE status = 'completed') / COUNT(*) FROM payments",
    invertTrend: false,
    seedValue: 96.8,
    seedPreviousValue: 95.4,
    drivers: [
      {
        id: 'omni-pay-method',
        label: 'By Payment Method',
        formula: "COUNT(WHERE status='completed') GROUP BY payment_method",
        sourceTable: 'payments',
        description: 'Credit card vs debit vs PayPal success rates differ',
        format: 'percentage',
        seedValue: 96.8,
        seedContribution: 48.3,
        seedTrend: 'up',
        seedChangePercent: 1.5,
      },
      {
        id: 'omni-pay-gateway',
        label: 'Gateway Reliability',
        formula: "COUNT(WHERE status='failed') / COUNT(*)",
        sourceTable: 'payments',
        description: 'Payment gateway uptime and error rates',
        format: 'percentage',
        seedValue: 3.2,
        seedContribution: 32.1,
        seedTrend: 'down',
        seedChangePercent: 0.8,
      },
      {
        id: 'omni-pay-conversion-impact',
        label: 'Conversion Impact',
        formula: 'payment_failed / total_journeys',
        sourceTable: 'customer_journeys',
        description: 'Payment failures that directly block willing buyers',
        format: 'percentage',
        seedValue: 3.2,
        seedContribution: 19.6,
        seedTrend: 'down',
        seedChangePercent: 0.8,
      },
    ],
    insights: [
      'Payment success rate improved 1.5pp, reducing conversion friction',
      'Credit card success rate highest at 98.2%, PayPal lowest at 94.1%',
      'Each 1pp improvement in payment success translates to ~18 additional orders',
    ],
  },
]

// ---------------------------------------------------------------------------
// Customer Engagement tab — 8 tiles
// ---------------------------------------------------------------------------

const customerEngagementMetrics: RegistryMetric[] = [
  {
    id: 'ce-active-rate',
    label: 'Active Customer Rate',
    format: 'percentage',
    unit: '%',
    icon: 'users',
    sourceTable: 'customer_snapshots',
    sql: "SELECT COUNT(WHERE activity_state = 'active') / COUNT(*) FROM customer_snapshots",
    invertTrend: false,
    seedValue: 68.4,
    seedPreviousValue: 65.9,
    drivers: [
      {
        id: 'ce-act-lapsed',
        label: 'Lapsed Customer Rate',
        formula: "COUNT(WHERE activity_state = 'lapsed') / COUNT(*)",
        sourceTable: 'customer_snapshots',
        description: 'Time since last purchase exceeds active threshold',
        format: 'percentage',
        seedValue: 23.4,
        seedContribution: 38.2,
        seedTrend: 'down',
        seedChangePercent: 2.1,
      },
      {
        id: 'ce-act-retention',
        label: 'Retention Rate',
        formula: '1 - churn_rate',
        sourceTable: 'customer_snapshots',
        description: 'Inverse of churn — fraction of customers retained',
        format: 'percentage',
        seedValue: 91.8,
        seedContribution: 34.6,
        seedTrend: 'up',
        seedChangePercent: 1.2,
      },
      {
        id: 'ce-act-transitions',
        label: 'Lifecycle State Transitions',
        formula: 'COUNT(*) GROUP BY activity_state across snapshots',
        sourceTable: 'customer_snapshots',
        description: 'Movement between New, Active, Lapsed, and Churned states',
        format: 'number',
        seedValue: 54012,
        seedContribution: 27.2,
        seedTrend: 'up',
        seedChangePercent: 3.8,
      },
    ],
    insights: [
      'Active rate up 2.5pp, driven by lapsed customer reactivation campaigns',
      'Retention rate at 91.8% shows strong overall customer loyalty',
      'Lifecycle transitions showing healthy new-to-active conversion pipeline',
    ],
  },
  {
    id: 'ce-churn-rate',
    label: 'Churn Rate',
    format: 'percentage',
    unit: '%',
    icon: 'warning',
    sourceTable: 'customer_snapshots',
    sql: 'SELECT COUNT(WHERE churned = TRUE) / COUNT(*) FROM customer_snapshots',
    invertTrend: true,
    seedValue: 8.2,
    seedPreviousValue: 9.1,
    drivers: [
      {
        id: 'ce-churn-recency',
        label: 'Days Since Last Purchase',
        formula: 'AVG(days_since_last_purchase)',
        sourceTable: 'customer_snapshots',
        description: 'Primary decay signal — longer gaps increase churn risk',
        format: 'number',
        seedValue: 42,
        seedContribution: 32.4,
        seedTrend: 'down',
        seedChangePercent: 4.2,
      },
      {
        id: 'ce-churn-unresponsive',
        label: 'Unresponsive Count',
        formula: 'AVG(unresponsive_count)',
        sourceTable: 'customer_snapshots',
        description: 'Campaigns sent with no response increase churn risk',
        format: 'number',
        seedValue: 3.4,
        seedContribution: 28.1,
        seedTrend: 'down',
        seedChangePercent: 6.8,
      },
      {
        id: 'ce-churn-spend-decline',
        label: 'Total Spend Decline',
        formula: 'Customers with stagnating total_spend relative to tenure',
        sourceTable: 'customer_snapshots',
        description: 'Declining spending pattern signals disengagement',
        format: 'percentage',
        seedValue: 12.3,
        seedContribution: 22.8,
        seedTrend: 'down',
        seedChangePercent: 3.1,
      },
      {
        id: 'ce-churn-service',
        label: 'Service Issues',
        formula: 'Unresolved or poorly-rated support tickets',
        sourceTable: 'support_tickets',
        description: 'Poor service experiences accelerate churn',
        format: 'number',
        seedValue: 89,
        seedContribution: 16.7,
        seedTrend: 'down',
        seedChangePercent: 8.4,
      },
    ],
    insights: [
      'Churn rate improved 9.9%, with unresponsive count reduction being the largest driver',
      'Recency gap shrinking indicates more frequent customer re-engagement',
      'Service issue resolution improvements directly reducing churn triggers',
    ],
  },
  {
    id: 'ce-open-rate',
    label: 'Campaign Open Rate',
    format: 'percentage',
    unit: '%',
    icon: 'mail',
    sourceTable: 'campaign_interactions',
    sql: 'SELECT COUNT(WHERE opened) / COUNT(*) FROM campaign_interactions',
    invertTrend: false,
    seedValue: 24.8,
    seedPreviousValue: 22.3,
    drivers: [
      {
        id: 'ce-open-by-type',
        label: 'Response by Campaign Type',
        formula: 'open_rate GROUP BY campaign_type',
        sourceTable: 'campaign_interactions',
        description: 'Email vs SMS vs push notification open rates differ',
        format: 'percentage',
        seedValue: 24.8,
        seedContribution: 42.6,
        seedTrend: 'up',
        seedChangePercent: 8.4,
      },
      {
        id: 'ce-open-by-segment',
        label: 'Response by Segment',
        formula: 'open_rate GROUP BY value_tier, rfm_segment',
        sourceTable: 'campaign_interactions',
        description: 'VIPs respond differently than at-risk customers',
        format: 'percentage',
        seedValue: 24.8,
        seedContribution: 34.8,
        seedTrend: 'up',
        seedChangePercent: 5.2,
      },
      {
        id: 'ce-open-fatigue',
        label: 'Campaign Fatigue',
        formula: 'AVG(unresponsive_count) and trend over time',
        sourceTable: 'campaign_interactions',
        description: 'Rising unresponsive counts signal over-messaging',
        format: 'number',
        seedValue: 3.4,
        seedContribution: 22.6,
        seedTrend: 'down',
        seedChangePercent: 6.8,
      },
    ],
    insights: [
      'Open rate up 11.2%, strongest gains from segmented campaign targeting',
      'SMS campaigns showing 31% open rate vs 22% for email — consider channel shift',
      'Campaign fatigue declining, indicating better send frequency management',
    ],
  },
  {
    id: 'ce-campaign-ctr',
    label: 'Campaign CTR',
    format: 'percentage',
    unit: '%',
    icon: 'cursor',
    sourceTable: 'campaign_interactions',
    sql: 'SELECT COUNT(WHERE clicked) / COUNT(*) FROM campaign_interactions',
    invertTrend: false,
    seedValue: 3.6,
    seedPreviousValue: 3.2,
    drivers: [
      {
        id: 'ce-ctr-ctor',
        label: 'Click-to-Open Rate',
        formula: 'COUNT(WHERE clicked) / COUNT(WHERE opened)',
        sourceTable: 'campaign_interactions',
        description: 'Content quality independent of subject line performance',
        format: 'percentage',
        seedValue: 14.5,
        seedContribution: 44.2,
        seedTrend: 'up',
        seedChangePercent: 6.1,
      },
      {
        id: 'ce-ctr-conversion',
        label: 'Campaign Conversion Rate',
        formula: 'COUNT(WHERE converted) / COUNT(*)',
        sourceTable: 'campaign_interactions',
        description: 'Full-funnel campaign effectiveness from send to purchase',
        format: 'percentage',
        seedValue: 1.8,
        seedContribution: 32.4,
        seedTrend: 'up',
        seedChangePercent: 8.3,
      },
      {
        id: 'ce-ctr-by-type',
        label: 'CTR by Campaign Type',
        formula: 'click_rate GROUP BY campaign_type',
        sourceTable: 'campaign_interactions',
        description: 'Different campaign types have different engagement patterns',
        format: 'percentage',
        seedValue: 3.6,
        seedContribution: 23.4,
        seedTrend: 'up',
        seedChangePercent: 4.8,
      },
    ],
    insights: [
      'CTR up 12.5%, click-to-open rate improvement suggests better content relevance',
      'Campaign conversion rate growing at 8.3%, strong downstream revenue impact',
      'Promotional campaigns outperforming transactional emails on CTR by 2.1x',
    ],
  },
  {
    id: 'ce-enrollment-rate',
    label: 'Loyalty Enrollment Rate',
    format: 'percentage',
    unit: '%',
    icon: 'star',
    sourceTable: 'loyalty_account',
    sql: 'SELECT COUNT(*) FROM loyalty_account / COUNT(*) FROM customers',
    invertTrend: false,
    seedValue: 42.1,
    seedPreviousValue: 39.8,
    drivers: [
      {
        id: 'ce-enr-points-bal',
        label: 'Avg Points Balance',
        formula: 'AVG(current_points)',
        sourceTable: 'loyalty_account',
        description: 'Active point accumulation indicates program engagement',
        format: 'number',
        seedValue: 2340,
        seedContribution: 36.4,
        seedTrend: 'up',
        seedChangePercent: 4.7,
      },
      {
        id: 'ce-enr-tier-dist',
        label: 'Tier Distribution',
        formula: 'COUNT(*) GROUP BY tier',
        sourceTable: 'loyalty_account',
        description: 'Standard, Silver, Gold, Platinum distribution',
        format: 'number',
        seedValue: 22739,
        seedContribution: 34.2,
        seedTrend: 'up',
        seedChangePercent: 5.8,
      },
      {
        id: 'ce-enr-lifetime',
        label: 'Lifetime Points Earned',
        formula: 'SUM(lifetime_points)',
        sourceTable: 'loyalty_account',
        description: 'Total points earned across all loyalty members',
        format: 'number',
        seedValue: 53214800,
        seedContribution: 29.4,
        seedTrend: 'up',
        seedChangePercent: 7.2,
      },
    ],
    insights: [
      'Enrollment rate up 5.8%, driven by sign-up incentives at checkout',
      'Points balance growing, indicating members are actively earning through purchases',
      'Gold and Platinum tiers growing fastest, showing program maturation',
    ],
  },
  {
    id: 'ce-redemption-rate',
    label: 'Points Redemption Rate',
    format: 'percentage',
    unit: '%',
    icon: 'refresh',
    sourceTable: 'points_transactions',
    sql: 'SELECT redeemed / issued FROM points_transactions',
    invertTrend: false,
    seedValue: 31.5,
    seedPreviousValue: 28.9,
    drivers: [
      {
        id: 'ce-red-issued',
        label: 'Points Issued',
        formula: 'SUM(points_change) WHERE points_change > 0',
        sourceTable: 'points_transactions',
        description: 'Purchase-driven accrual plus bonus promotions',
        format: 'number',
        seedValue: 4821000,
        seedContribution: 38.6,
        seedTrend: 'up',
        seedChangePercent: 7.2,
      },
      {
        id: 'ce-red-redeemed',
        label: 'Points Redeemed',
        formula: 'SUM(ABS(points_change)) WHERE points_change < 0',
        sourceTable: 'points_transactions',
        description: 'Higher redemption indicates more engaged loyalty members',
        format: 'number',
        seedValue: 1518615,
        seedContribution: 34.8,
        seedTrend: 'up',
        seedChangePercent: 9.0,
      },
      {
        id: 'ce-red-reasons',
        label: 'Transaction Reasons',
        formula: 'COUNT(*) GROUP BY reason',
        sourceTable: 'points_transactions',
        description: 'Purchase earn, redemption, bonus, promo breakdown',
        format: 'number',
        seedValue: 38420,
        seedContribution: 26.6,
        seedTrend: 'up',
        seedChangePercent: 3.4,
      },
    ],
    insights: [
      'Redemption rate up 9.0%, indicating growing loyalty program engagement',
      'Points issuance outpacing redemption, building long-term program liability',
      'Bonus promotions driving 22% of new points issued, effective for engagement',
    ],
  },
  {
    id: 'ce-resolution-rate',
    label: 'Ticket Resolution Rate',
    format: 'percentage',
    unit: '%',
    icon: 'check',
    sourceTable: 'support_tickets',
    sql: "SELECT COUNT(WHERE status = 'resolved') / COUNT(*) FROM support_tickets",
    invertTrend: false,
    seedValue: 87.3,
    seedPreviousValue: 84.1,
    drivers: [
      {
        id: 'ce-res-open',
        label: 'Open Tickets',
        formula: "COUNT(WHERE status = 'open')",
        sourceTable: 'support_tickets',
        description: 'Resolution capacity vs creation rate determines backlog',
        format: 'number',
        seedValue: 142,
        seedContribution: 38.4,
        seedTrend: 'down',
        seedChangePercent: 12.3,
      },
      {
        id: 'ce-res-time',
        label: 'Avg Resolution Time',
        formula: 'AVG(resolved_at - created_at)',
        sourceTable: 'support_tickets',
        description: 'Resolution speed driven by staff efficiency and issue complexity',
        format: 'number',
        seedValue: 4.2,
        seedContribution: 34.2,
        seedTrend: 'down',
        seedChangePercent: 8.6,
      },
      {
        id: 'ce-res-by-type',
        label: 'Tickets by Issue Type',
        formula: 'COUNT(*) GROUP BY issue_type',
        sourceTable: 'support_tickets',
        description: 'Distribution identifies systemic problems',
        format: 'number',
        seedValue: 1120,
        seedContribution: 27.4,
        seedTrend: 'neutral',
        seedChangePercent: 1.2,
      },
    ],
    insights: [
      'Resolution rate up 3.8%, open ticket backlog reduced 12.3%',
      'Average resolution time improved 8.6%, faster turnaround for customers',
      'Shipping-related tickets remain the largest category at 34% of volume',
    ],
  },
  {
    id: 'ce-satisfaction',
    label: 'Avg Satisfaction Rating',
    format: 'number',
    unit: '/5',
    icon: 'star',
    sourceTable: 'support_tickets',
    sql: 'SELECT AVG(satisfaction_rating) FROM support_tickets',
    invertTrend: false,
    seedValue: 4.2,
    seedPreviousValue: 4.0,
    drivers: [
      {
        id: 'ce-sat-by-type',
        label: 'Satisfaction by Issue Type',
        formula: 'AVG(satisfaction_rating) GROUP BY issue_type',
        sourceTable: 'support_tickets',
        description: 'Some issue types consistently produce lower satisfaction',
        format: 'number',
        seedValue: 4.2,
        seedContribution: 42.8,
        seedTrend: 'up',
        seedChangePercent: 5.0,
      },
      {
        id: 'ce-sat-resolution-speed',
        label: 'Resolution Speed Impact',
        formula: 'AVG(satisfaction_rating) by resolution time bucket',
        sourceTable: 'support_tickets',
        description: 'Faster resolution strongly correlates with higher satisfaction',
        format: 'number',
        seedValue: 4.2,
        seedContribution: 34.6,
        seedTrend: 'up',
        seedChangePercent: 3.8,
      },
      {
        id: 'ce-sat-total-tickets',
        label: 'Total Tickets',
        formula: 'COUNT(*)',
        sourceTable: 'support_tickets',
        description: 'Overall ticket volume from service_issue_probability config',
        format: 'number',
        seedValue: 1120,
        seedContribution: 22.6,
        seedTrend: 'down',
        seedChangePercent: 4.2,
      },
    ],
    insights: [
      'Satisfaction up 5.0%, driven by faster resolution times across all issue types',
      'Return-related tickets have lowest satisfaction (3.6/5), opportunity for improvement',
      'Ticket volume declining 4.2%, suggesting fewer product/service issues overall',
    ],
  },
]

// ---------------------------------------------------------------------------
// Inventory Replenishment tab — 8 tiles
// ---------------------------------------------------------------------------

const inventoryReplenishmentMetrics: RegistryMetric[] = [
  {
    id: 'ir-qty-on-hand',
    label: 'Total Qty on Hand',
    format: 'number',
    unit: '',
    icon: 'boxes',
    sourceTable: 'inventory',
    sql: 'SELECT SUM(quantity_on_hand) FROM inventory',
    invertTrend: false,
    seedValue: 48720,
    seedPreviousValue: 46380,
    drivers: [
      {
        id: 'ir-qty-by-location',
        label: 'Quantity by Location',
        formula: 'SUM(quantity_on_hand) GROUP BY location_id',
        sourceTable: 'inventory',
        description: 'Demand variance across stores and warehouse',
        format: 'number',
        seedValue: 48720,
        seedContribution: 38.4,
        seedTrend: 'up',
        seedChangePercent: 5.0,
      },
      {
        id: 'ir-qty-reserved',
        label: 'Reserved Inventory',
        formula: 'SUM(quantity_reserved)',
        sourceTable: 'inventory',
        description: 'Open orders awaiting fulfillment reduce available stock',
        format: 'number',
        seedValue: 3240,
        seedContribution: 28.2,
        seedTrend: 'up',
        seedChangePercent: 3.2,
      },
      {
        id: 'ir-qty-on-order',
        label: 'On-Order Inventory',
        formula: 'SUM(on_order_qty)',
        sourceTable: 'inventory',
        description: 'Purchase orders placed but not yet received',
        format: 'number',
        seedValue: 12480,
        seedContribution: 22.1,
        seedTrend: 'up',
        seedChangePercent: 8.4,
      },
      {
        id: 'ir-qty-days-supply',
        label: 'Days of Supply',
        formula: 'quantity_on_hand / daily_demand',
        sourceTable: 'inventory_snapshots',
        description: 'Low values signal upcoming stockout risk',
        format: 'number',
        seedValue: 34.2,
        seedContribution: 11.3,
        seedTrend: 'down',
        seedChangePercent: 12.1,
      },
    ],
    insights: [
      'Inventory up 5.0% with on-order stock providing additional pipeline coverage',
      'Days of supply declining 12.1%, watch for potential stockout risk in high-velocity SKUs',
      'Reserved inventory growing at 3.2%, reflecting healthy order flow',
    ],
  },
  {
    id: 'ir-below-reorder',
    label: 'Items Below Reorder Point',
    format: 'number',
    unit: '',
    icon: 'warning',
    sourceTable: 'inventory',
    sql: 'SELECT COUNT(WHERE quantity_on_hand <= reorder_point) FROM inventory',
    invertTrend: true,
    seedValue: 23,
    seedPreviousValue: 18,
    drivers: [
      {
        id: 'ir-bel-demand-spike',
        label: 'Demand Spikes',
        formula: 'SKUs with daily_demand > 2x avg',
        sourceTable: 'inventory_snapshots',
        description: 'Unexpected demand surges deplete stock below reorder thresholds',
        format: 'number',
        seedValue: 8,
        seedContribution: 42.3,
        seedTrend: 'up',
        seedChangePercent: 14.3,
      },
      {
        id: 'ir-bel-slow-delivery',
        label: 'Slow Supplier Deliveries',
        formula: 'AVG(actual_lead_time - expected_lead_time) WHERE late',
        sourceTable: 'supplier_deliveries',
        description: 'Late deliveries leave gaps in replenishment cycle',
        format: 'number',
        seedValue: 2.1,
        seedContribution: 34.8,
        seedTrend: 'up',
        seedChangePercent: 8.2,
      },
      {
        id: 'ir-bel-safety-stock',
        label: 'Safety Stock Coverage',
        formula: 'AVG(safety_stock / daily_demand)',
        sourceTable: 'replenishment_policy',
        description: 'Insufficient safety stock buffer for demand variability',
        format: 'number',
        seedValue: 5.2,
        seedContribution: 22.9,
        seedTrend: 'down',
        seedChangePercent: 3.1,
      },
    ],
    insights: [
      'Items below reorder point increased 27.8% — demand spikes are the primary driver',
      'Slow supplier deliveries contributing to reorder point breaches',
      'Safety stock levels declining, consider adjusting buffer calculations',
    ],
  },
  {
    id: 'ir-stockout-count',
    label: 'Stockout Count',
    format: 'number',
    unit: '',
    icon: 'warning',
    sourceTable: 'inventory_events',
    sql: 'SELECT COUNT(WHERE stockout_occurred = TRUE) FROM inventory_events',
    invertTrend: true,
    seedValue: 47,
    seedPreviousValue: 52,
    drivers: [
      {
        id: 'ir-so-demand-rate',
        label: 'Demand Rate',
        formula: 'daily_demand from inventory_snapshots',
        sourceTable: 'inventory_snapshots',
        description: 'Consumption velocity determines how fast stock depletes',
        format: 'number',
        seedValue: 1423,
        seedContribution: 28.4,
        seedTrend: 'up',
        seedChangePercent: 4.3,
      },
      {
        id: 'ir-so-reorder-point',
        label: 'Reorder Point Adequacy',
        formula: 'reorder_point from replenishment_policy',
        sourceTable: 'replenishment_policy',
        description: 'If set too low, purchase orders trigger too late',
        format: 'number',
        seedValue: 150,
        seedContribution: 24.2,
        seedTrend: 'neutral',
        seedChangePercent: 0.0,
      },
      {
        id: 'ir-so-lead-time',
        label: 'Supplier Lead Time',
        formula: 'actual_lead_time_days from supplier_deliveries',
        sourceTable: 'supplier_deliveries',
        description: 'Longer lead time = higher stockout risk during replenishment gap',
        format: 'number',
        seedValue: 8.5,
        seedContribution: 22.8,
        seedTrend: 'down',
        seedChangePercent: 7.6,
      },
      {
        id: 'ir-so-shrinkage',
        label: 'Shrinkage',
        formula: "event_type = 'shrinkage' events",
        sourceTable: 'inventory_events',
        description: 'Silent stock erosion from damage, theft, or expiration',
        format: 'number',
        seedValue: 584,
        seedContribution: 14.2,
        seedTrend: 'down',
        seedChangePercent: 2.1,
      },
      {
        id: 'ir-so-reliability',
        label: 'Supplier Reliability',
        formula: 'on_time flag and short_shipped flag',
        sourceTable: 'supplier_deliveries',
        description: 'Unreliable suppliers compound lead time uncertainty',
        format: 'percentage',
        seedValue: 82.5,
        seedContribution: 10.4,
        seedTrend: 'up',
        seedChangePercent: 3.2,
      },
    ],
    insights: [
      'Stockout count down 9.6%, driven by improved supplier lead times',
      'Demand rate growing 4.3%, putting pressure on reorder point adequacy',
      'Shrinkage reduction of 2.1% providing incremental stock availability improvement',
    ],
  },
  {
    id: 'ir-fill-rate',
    label: 'Fill Rate',
    format: 'percentage',
    unit: '%',
    icon: 'check',
    sourceTable: 'inventory_events',
    sql: 'SELECT 1 - (stockout_events / demand_events) FROM inventory_events',
    invertTrend: false,
    seedValue: 94.3,
    seedPreviousValue: 91.8,
    drivers: [
      {
        id: 'ir-fill-stockout-rate',
        label: 'Stockout Rate',
        formula: 'stockout_events / total_demand_events',
        sourceTable: 'inventory_events',
        description: 'Reorder point, lead time, and demand spike interaction',
        format: 'percentage',
        seedValue: 5.7,
        seedContribution: 42.6,
        seedTrend: 'down',
        seedChangePercent: 9.6,
      },
      {
        id: 'ir-fill-duration',
        label: 'Stockout Duration',
        formula: 'SUM(stockout_hours)',
        sourceTable: 'inventory_snapshots',
        description: 'Time from depletion to replenishment receipt',
        format: 'number',
        seedValue: 142,
        seedContribution: 32.8,
        seedTrend: 'down',
        seedChangePercent: 14.2,
      },
      {
        id: 'ir-fill-by-sku',
        label: 'Stockout by SKU',
        formula: 'COUNT(*) GROUP BY sku WHERE stockout_occurred',
        sourceTable: 'inventory_events',
        description: 'Identifies chronic problem items for targeted intervention',
        format: 'number',
        seedValue: 47,
        seedContribution: 24.6,
        seedTrend: 'down',
        seedChangePercent: 9.6,
      },
    ],
    insights: [
      'Fill rate up 2.7pp, reflecting reduced stockout frequency and duration',
      'Stockout duration down 14.2%, indicating faster replenishment response',
      'Chronic stockout SKUs reduced from 52 to 47, focused intervention working',
    ],
  },
  {
    id: 'ir-supplier-ontime',
    label: 'Supplier On-Time %',
    format: 'percentage',
    unit: '%',
    icon: 'truck',
    sourceTable: 'supplier_deliveries',
    sql: 'SELECT COUNT(WHERE on_time) / COUNT(*) FROM supplier_deliveries',
    invertTrend: false,
    seedValue: 82.5,
    seedPreviousValue: 79.8,
    drivers: [
      {
        id: 'ir-sup-lead-var',
        label: 'Lead Time Variance',
        formula: 'STDDEV(actual_lead_time_days)',
        sourceTable: 'supplier_deliveries',
        description: 'Higher variance = less predictable replenishment timing',
        format: 'number',
        seedValue: 2.3,
        seedContribution: 38.4,
        seedTrend: 'down',
        seedChangePercent: 6.2,
      },
      {
        id: 'ir-sup-accuracy',
        label: 'Lead Time Accuracy',
        formula: 'AVG(actual_lead_time_days - expected_lead_time_days)',
        sourceTable: 'supplier_deliveries',
        description: 'Positive values mean late; negative mean early delivery',
        format: 'number',
        seedValue: 0.8,
        seedContribution: 32.1,
        seedTrend: 'down',
        seedChangePercent: 12.3,
      },
      {
        id: 'ir-sup-short-ship',
        label: 'Short Shipment Rate',
        formula: 'COUNT(WHERE short_shipped) / COUNT(*)',
        sourceTable: 'supplier_deliveries',
        description: 'Partial deliveries require additional POs and extend lead time',
        format: 'percentage',
        seedValue: 8.4,
        seedContribution: 29.5,
        seedTrend: 'down',
        seedChangePercent: 4.8,
      },
    ],
    insights: [
      'Supplier on-time delivery up 3.4%, lead time accuracy is the biggest improvement',
      'Lead time variance declining, providing more predictable replenishment scheduling',
      'Short shipment rate down 4.8%, fewer partial deliveries requiring follow-up POs',
    ],
  },
  {
    id: 'ir-avg-lead-time',
    label: 'Avg Lead Time',
    format: 'number',
    unit: 'days',
    icon: 'clock',
    sourceTable: 'supplier_deliveries',
    sql: 'SELECT AVG(actual_lead_time_days) FROM supplier_deliveries',
    invertTrend: true,
    seedValue: 8.5,
    seedPreviousValue: 9.2,
    drivers: [
      {
        id: 'ir-lt-by-supplier',
        label: 'By Supplier Performance',
        formula: 'AVG(actual_lead_time_days) GROUP BY supplier_id',
        sourceTable: 'supplier_deliveries',
        description: 'Identifies best and worst performing suppliers',
        format: 'number',
        seedValue: 8.5,
        seedContribution: 42.3,
        seedTrend: 'down',
        seedChangePercent: 7.6,
      },
      {
        id: 'ir-lt-qty-effect',
        label: 'Order Quantity Effect',
        formula: 'CORR(order_quantity, actual_lead_time_days)',
        sourceTable: 'supplier_deliveries',
        description: 'Larger orders may take longer to fulfill',
        format: 'number',
        seedValue: 0.34,
        seedContribution: 28.4,
        seedTrend: 'neutral',
        seedChangePercent: 1.2,
      },
      {
        id: 'ir-lt-received-vs-ordered',
        label: 'Received vs Ordered',
        formula: 'SUM(received_quantity) / SUM(order_quantity)',
        sourceTable: 'supplier_deliveries',
        description: 'Quantity fill rate from suppliers',
        format: 'percentage',
        seedValue: 94.8,
        seedContribution: 29.3,
        seedTrend: 'up',
        seedChangePercent: 2.4,
      },
    ],
    insights: [
      'Average lead time improved 7.6%, strongest gains from top-3 suppliers',
      'Quantity fill rate at 94.8%, short shipments still impacting 5.2% of deliveries',
      'Larger orders showing modest correlation with longer lead times (r=0.34)',
    ],
  },
  {
    id: 'ir-turnover',
    label: 'Inventory Turnover',
    format: 'number',
    unit: 'x',
    icon: 'cycle',
    sourceTable: 'inventory_snapshots',
    sql: 'SELECT SUM(daily_demand) * 365 / AVG(quantity_on_hand) FROM inventory_snapshots',
    invertTrend: false,
    seedValue: 6.8,
    seedPreviousValue: 6.2,
    drivers: [
      {
        id: 'ir-turn-po-count',
        label: 'Total POs Issued',
        formula: 'COUNT(*)',
        sourceTable: 'purchase_orders',
        description: 'Reorder frequency driven by demand and reorder point',
        format: 'number',
        seedValue: 342,
        seedContribution: 36.4,
        seedTrend: 'up',
        seedChangePercent: 8.4,
      },
      {
        id: 'ir-turn-po-status',
        label: 'PO Status Distribution',
        formula: 'COUNT(*) GROUP BY status',
        sourceTable: 'purchase_orders',
        description: 'PENDING vs RECEIVED completion rate',
        format: 'number',
        seedValue: 342,
        seedContribution: 28.2,
        seedTrend: 'up',
        seedChangePercent: 4.2,
      },
      {
        id: 'ir-turn-reorder-trigger',
        label: 'Reorder Trigger Rate',
        formula: 'COUNT(WHERE reorder_triggered) / COUNT(*)',
        sourceTable: 'inventory_snapshots',
        description: 'How often stock hits reorder point',
        format: 'percentage',
        seedValue: 18.4,
        seedContribution: 35.4,
        seedTrend: 'up',
        seedChangePercent: 6.1,
      },
    ],
    insights: [
      'Inventory turnover up 9.7%, indicating more efficient use of inventory investment',
      'Reorder trigger rate rising at 6.1%, healthy signal of demand-driven replenishment',
      'PO completion rate improving, fewer stuck orders in PENDING status',
    ],
  },
  {
    id: 'ir-shrinkage-rate',
    label: 'Shrinkage Rate',
    format: 'percentage',
    unit: '%',
    icon: 'warning',
    sourceTable: 'inventory_events',
    sql: "SELECT SUM(ABS(quantity_change) WHERE event_type='shrinkage') / total_stock FROM inventory_events",
    invertTrend: true,
    seedValue: 1.2,
    seedPreviousValue: 1.4,
    drivers: [
      {
        id: 'ir-shr-by-type',
        label: 'Shrinkage by Type',
        formula: "SUM(ABS(quantity_change)) GROUP BY shrinkage_type WHERE event_type='shrinkage'",
        sourceTable: 'inventory_events',
        description: 'Damage, theft, and expiration contribute differently',
        format: 'number',
        seedValue: 584,
        seedContribution: 44.2,
        seedTrend: 'down',
        seedChangePercent: 8.4,
      },
      {
        id: 'ir-shr-config-rate',
        label: 'Daily Shrinkage Rate',
        formula: 'daily_shrinkage_rate from config',
        sourceTable: 'inventory_events',
        description: 'Configured baseline shrinkage rate per day',
        format: 'percentage',
        seedValue: 0.03,
        seedContribution: 32.4,
        seedTrend: 'neutral',
        seedChangePercent: 0.0,
      },
      {
        id: 'ir-shr-stock-impact',
        label: 'Inventory Impact',
        formula: 'SUM(shrinkage_qty) / SUM(quantity_on_hand)',
        sourceTable: 'inventory_events',
        description: 'Net stock reduction from all shrinkage events',
        format: 'percentage',
        seedValue: 1.2,
        seedContribution: 23.4,
        seedTrend: 'down',
        seedChangePercent: 14.3,
      },
    ],
    insights: [
      'Shrinkage rate down 14.3%, significant improvement in inventory preservation',
      'Damage-related shrinkage reduced the most, improved handling procedures working',
      'Net inventory impact declining, freeing up stock for fulfillment',
    ],
  },
]

// ---------------------------------------------------------------------------
// Registry map & lookups
// ---------------------------------------------------------------------------

const allMetrics: RegistryMetric[] = [
  ...mainMetrics,
  ...omnichannelMetrics,
  ...customerEngagementMetrics,
  ...inventoryReplenishmentMetrics,
]

const registryMap = new Map<string, RegistryMetric>(
  allMetrics.map((m) => [m.id, m])
)

const tabMetrics: Partial<Record<TabId, RegistryMetric[]>> = {
  main: mainMetrics,
  omnichannel: omnichannelMetrics,
  'customer-engagement': customerEngagementMetrics,
  'inventory-replenishment': inventoryReplenishmentMetrics,
}

// ---------------------------------------------------------------------------
// Conversion utilities
// ---------------------------------------------------------------------------

function generateSparkline(previousValue: number, currentValue: number): number[] {
  return Array.from({ length: 20 }, (_, i) => {
    const progress = i / 19
    const variation = Math.sin(i * 0.5) * 0.1
    return previousValue + (currentValue - previousValue) * progress + variation * currentValue
  })
}

function registryToMetricData(reg: RegistryMetric): MetricData {
  const changePercent =
    ((reg.seedValue - reg.seedPreviousValue) / reg.seedPreviousValue) * 100
  const trend: 'up' | 'down' | 'neutral' =
    changePercent > 0 ? 'up' : changePercent < 0 ? 'down' : 'neutral'

  return {
    id: reg.id,
    label: reg.label,
    value: reg.seedValue,
    previousValue: reg.seedPreviousValue,
    unit: reg.unit,
    format: reg.format,
    trend,
    changePercent: Math.abs(changePercent),
    icon: reg.icon,
    invertTrend: reg.invertTrend,
    sparklineData: generateSparkline(reg.seedPreviousValue, reg.seedValue),
    ...(reg.forecast ? { forecast: reg.forecast } : {}),
  }
}

function registryToBreakdown(reg: RegistryMetric): MetricBreakdown {
  return {
    metricId: reg.id,
    drivers: reg.drivers.map((d) => ({
      id: d.id,
      label: d.label,
      value: d.seedValue,
      contribution: d.seedContribution,
      trend: d.seedTrend,
      changePercent: d.seedChangePercent,
      description: d.description,
      format: d.format,
    })),
    insights: reg.insights,
  }
}

// ---------------------------------------------------------------------------
// Public API — drop-in replacements for mock-data.ts
// ---------------------------------------------------------------------------

export function generateMockMetrics(): MetricData[] {
  return mainMetrics.map(registryToMetricData)
}

export function generateOmnichannelMetrics(): MetricData[] {
  return omnichannelMetrics.map(registryToMetricData)
}

export function generateCustomerEngagementMetrics(): MetricData[] {
  return customerEngagementMetrics.map(registryToMetricData)
}

export function generateInventoryReplenishmentMetrics(): MetricData[] {
  return inventoryReplenishmentMetrics.map(registryToMetricData)
}

export function generateMetricBreakdown(metricId: string): MetricBreakdown {
  const reg = registryMap.get(metricId)
  if (!reg) return { metricId, drivers: [], insights: [] }
  return registryToBreakdown(reg)
}

// ---------------------------------------------------------------------------
// Additional registry access
// ---------------------------------------------------------------------------

export function getRegistryMetric(id: string): RegistryMetric | undefined {
  return registryMap.get(id)
}

export function isInvertedTrend(id: string): boolean {
  return registryMap.get(id)?.invertTrend ?? false
}

export function getMetricsForTab(tabId: TabId): RegistryMetric[] {
  return tabMetrics[tabId] ?? []
}
